# Do not insert a blank line between shell prompts
add_newline = false

[username]
show_always = true
style_user = "bold blue"
format = "[$user]($style) on "

[hostname]
ssh_only = false
format = "[$hostname](bold green) "
#trim_at = ".companyname.com"

[directory]
style = "bold 8"
format = "[\\[$path\\]]($style)[$read_only]($read_only_style) "
truncate_to_repo = false
truncation_length = 0
#truncation_symbol = "…/"

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

#[status]
#disabled = false

#[line_break]
#disabled = true

#[time]
#disabled = false

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true