InlayHints:
  Enabled: Yes
Diagnostics:
  UnusedIncludes: Strict # None
  MissingIncludes: Strict # None
  ClangTidy:
    FastCheckFilter: Strict # Loose, None
    Add: [
        cert-*,
        hicpp-*,
        bugprone-*,
        clang-analyzer-*,
        clang-diagnostic-*,
        cppcoreguidelines-*,
        modernize-*,
        performance-*,
        portability-*,
        readability-*,
        concurrency-*,
      ] # https://clang.llvm.org/extra/clang-tidy/
